version: '3.8'
services:
 php-apache-environment:
  container_name: php-apache
  build:
   context: ./
   dockerfile: Dockerfile 
  depends_on:
   - db
  volumes: 
   - ./docker/www:/var/www/html/
  ports:
   - 8000:80
 db:
  container_name: db
  image: mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: abcd
   MYSQL_DATABASE: database
   MYSQL_USER: user
   MYSQL_PASSWORD: abcd
  volumes: 
   - ./docker/db:/var/lib/mysql/
  ports:
   - "3306:3306"
